server:
  http:
    hostname: localhost
    port: 7000
    static:
      production:
        /public: server/public
        /assets: dist/assets
        /dist: dist
  redis:
    port: 6379
    host: redis.kubesphere-system.svc
  redisTimeout: 5000
  sessionTimeout: 7200000
client:
  version:
    kubesphere: v3.1.0
    kubernetes: v1.20.0
    openpitrix: v3.1.0
  enableKubeConfig: true
defaultClusterName: default
